/**
 * Copyright (c) 2026 Ada Technology. All rights reserved.
 *
 * This source code is proprietary and confidential. Unauthorized copying,
 * modification, distribution, or use of this file, via any medium, is
 * strictly prohibited without prior written permission from Ada Technology.
 */

export const ERROR_CODES = {
  shared: {
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    RATE_LIMITED: 'RATE_LIMITED',
  },
  agent: {
    INVALID_CREDENTIALS: 'AGENT_INVALID_CREDENTIALS',
    NOT_AUTHENTICATED: 'AGENT_NOT_AUTHENTICATED',
    NOT_AUTHORIZED: 'AGENT_NOT_AUTHORIZED',
    NOT_FOUND: 'AGENT_NOT_FOUND',
    EMAIL_ALREADY_EXISTS: 'AGENT_EMAIL_ALREADY_EXISTS',
  },
  conversation: {
    NOT_FOUND: 'CONVERSATION_NOT_FOUND',
    ALREADY_ASSIGNED: 'CONVERSATION_ALREADY_ASSIGNED',
    NOT_ASSIGNED_TO_AGENT: 'CONVERSATION_NOT_ASSIGNED_TO_AGENT',
    CLOSED: 'CONVERSATION_CLOSED',
    OUTSIDE_SERVICE_WINDOW: 'CONVERSATION_OUTSIDE_SERVICE_WINDOW',
  },
  panel: {
    REALTIME_TICKET_INVALID: 'PANEL_REALTIME_TICKET_INVALID',
  },
  flow: {
    NOT_FOUND: 'FLOW_NOT_FOUND',
    NO_PUBLISHED_VERSION: 'FLOW_NO_PUBLISHED_VERSION',
    INVALID_GRAPH: 'FLOW_INVALID_GRAPH',
    ENTRY_NODE_MISSING: 'FLOW_ENTRY_NODE_MISSING',
    NODE_NOT_FOUND: 'FLOW_NODE_NOT_FOUND',
    KEY_MISMATCH: 'FLOW_KEY_MISMATCH',
    VERSION_CONFLICT: 'FLOW_VERSION_CONFLICT',
    ROOT_NOT_DELETABLE: 'FLOW_ROOT_NOT_DELETABLE',
    KEY_ALREADY_EXISTS: 'FLOW_KEY_ALREADY_EXISTS',
  },
  knowledge: {
    ITEM_NOT_FOUND: 'KNOWLEDGE_ITEM_NOT_FOUND',
    SLUG_ALREADY_EXISTS: 'KNOWLEDGE_SLUG_ALREADY_EXISTS',
  },
  lead: {
    NOT_FOUND: 'LEAD_NOT_FOUND',
  },
  channel: {
    UNSUPPORTED: 'CHANNEL_UNSUPPORTED',
    WIDGET_ORIGIN_NOT_ALLOWED: 'CHANNEL_WIDGET_ORIGIN_NOT_ALLOWED',
    WIDGET_AUDIO_UNAVAILABLE: 'CHANNEL_WIDGET_AUDIO_UNAVAILABLE',
    WIDGET_AUDIO_INVALID: 'CHANNEL_WIDGET_AUDIO_INVALID',
    WIDGET_AUDIO_NOT_UNDERSTOOD: 'CHANNEL_WIDGET_AUDIO_NOT_UNDERSTOOD',
    WIDGET_AUDIO_BUSY: 'CHANNEL_WIDGET_AUDIO_BUSY',
    WIDGET_AUDIO_FAILED: 'CHANNEL_WIDGET_AUDIO_FAILED',
    WHATSAPP_DISABLED: 'CHANNEL_WHATSAPP_DISABLED',
    WHATSAPP_INVALID_SIGNATURE: 'CHANNEL_WHATSAPP_INVALID_SIGNATURE',
    WHATSAPP_SEND_FAILED: 'CHANNEL_WHATSAPP_SEND_FAILED',
    WHATSAPP_TEMPLATE_REQUEST_FAILED: 'CHANNEL_WHATSAPP_TEMPLATE_REQUEST_FAILED',
  },
} as const;
